'use strict';

const crypto = require('crypto');
const { encrypt } = require('./crypto');

/**
 * Generate a random short ID
 */
function generateId() {
  return 'enc-' + crypto.randomBytes(4).toString('hex');
}

/**
 * Parse HTML tag attributes into a key-value object
 * @param {string} attrString
 * @returns {Record<string, string>}
 */
function parseAttributes(attrString) {
  const attrs = {};
  if (!attrString) return attrs;

  const regex = /([a-zA-Z0-9_-]+)(?:=(?:["']([^"']*)["']|([^\s>]+)))?/g;
  let match;
  while ((match = regex.exec(attrString)) !== null) {
    const key = match[1].toLowerCase();
    const value = match[2] !== undefined ? match[2] : (match[3] !== undefined ? match[3] : true);
    attrs[key] = value;
  }
  return attrs;
}

/**
 * Convert any remaining markdown image or link syntax into HTML
 * @param {string} text
 * @returns {string}
 */
function renderMarkdownImages(text) {
  if (!text) return text;
  // Markdown images: ![alt](url "title")
  return text.replace(/!\[([^\]]*)\]\(([^)\s]+)(?:\s+["']([^"']*)["'])?\)/g, (match, alt, url, title) => {
    const titleAttr = title ? ` title="${escapeHtml(title)}"` : '';
    return `<img src="${url}" alt="${escapeHtml(alt)}"${titleAttr}>`;
  });
}

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Generate default placeholder HTML when <placeholder> is not specified:
 * - Replaces text nodes with default_text_placeholder (e.g. '***')
 * - Preserves blurred <img> tags generated by imageProcessor
 * - Preserves structural HTML tags (<p>, <div>, <b>, <ul>, etc.)
 *
 * @param {string} blurredHtml - HTML with blurred images already substituted
 * @param {string} defaultTextPlaceholder - Replacement string for text, e.g. '***'
 * @returns {string}
 */
function generateDefaultPlaceholder(blurredHtml, defaultTextPlaceholder = '***') {
  if (!blurredHtml) return `<span class="h-mask-txt hexo-encrypt-mask">${defaultTextPlaceholder}</span>`;

  // Split by HTML tags
  const tokens = blurredHtml.split(/(<[^>]+>)/g);
  let result = '';
  let hasImage = false;
  let hasMaskedText = false;

  for (const token of tokens) {
    if (!token) continue;

    if (token.startsWith('<') && token.endsWith('>')) {
      // It's a tag
      if (token.toLowerCase().startsWith('<img')) {
        hasImage = true;
        result += token;
      } else {
        // Keep non-image tag intact
        result += token;
      }
    } else {
      // It's text
      const trimmed = token.trim();
      if (trimmed.length > 0) {
        // Replace non-whitespace text with placeholder
        hasMaskedText = true;
        const masked = `<span class="h-mask-txt hexo-encrypt-mask">${escapeHtml(defaultTextPlaceholder)}</span>`;
        // Preserve leading and trailing whitespace
        const leading = token.match(/^\s*/)[0];
        const trailing = token.match(/\s*$/)[0];
        result += leading + masked + trailing;
      } else {
        result += token;
      }
    }
  }

  // If result is empty or purely whitespace
  if (!result.trim()) {
    result = `<span class="h-mask-txt hexo-encrypt-mask">${escapeHtml(defaultTextPlaceholder)}</span>`;
  }

  return result;
}

/**
 * Determine if content is inline or block
 * @param {string} content
 * @returns {boolean} true if block, false if inline
 */
function isBlockContent(content) {
  if (!content) return false;
  return /<(?:p|div|h[1-6]|ul|ol|li|blockquote|table|pre|hr|section|article|figure)\b/i.test(content) ||
    content.includes('\n\n');
}

/**
 * Parse and process encrypt tags in post content
 *
 * @param {string} content - Post content HTML
 * @param {object} postData - Post metadata from Hexo
 * @param {object} config - Plugin configuration
 * @param {ImageProcessor} imageProcessor - Image processor instance
 * @returns {Promise<{ content: string, hasEncryptedContent: boolean }>}
 */
async function parseAndEncrypt(content, postData, config, imageProcessor) {
  if (!content || typeof content !== 'string') {
    return { content, hasEncryptedContent: false };
  }

  const tagNames = config.tag_names || ['encrypt', 'hexo-encrypt', 'secret'];
  const placeholderTagNames = config.placeholder_tag_names || ['placeholder', 'encrypt-placeholder', 'hexo-placeholder'];
  const contentTagNames = config.content_tag_names || ['content', 'encrypt-content'];

  const tagPattern = tagNames.join('|');
  const placeholderPattern = placeholderTagNames.join('|');
  const contentPattern = contentTagNames.join('|');

  // Match: <encrypt(attr)>...</encrypt>
  const encryptRegex = new RegExp(
    `<(${tagPattern})\\b([^>]*)>([\\s\\S]*?)<\\/\\1>`,
    'gi'
  );

  let match;
  let hasEncryptedContent = false;
  let processedContent = content;

  // We find matches sequentially
  const blocksToProcess = [];
  while ((match = encryptRegex.exec(content)) !== null) {
    blocksToProcess.push({
      fullMatch: match[0],
      tagName: match[1],
      attrString: match[2],
      innerContent: match[3],
      index: match.index
    });
  }

  if (blocksToProcess.length === 0) {
    return { content, hasEncryptedContent: false };
  }

  hasEncryptedContent = true;

  for (const block of blocksToProcess) {
    const attrs = parseAttributes(block.attrString);

    // Determine password
    // Precedence: tag attr > post front-matter (password or encrypt.password) > site config
    const postPassword = (postData && (postData.password || (postData.encrypt && postData.encrypt.password) || (postData.encryption && postData.encryption.password))) || '';
    const password = attrs.password || attrs.pass || postPassword || config.password;

    if (!password) {
      if (!config.silent) {
        console.warn(`[hexo-encryption-auto] Warning: No password provided for encrypted block in "${postData.title || postData.slug || 'untitled'}". Content will be unencrypted.`);
      }
      continue;
    }

    const hint = attrs.hint || postData.hint || (postData.encrypt && postData.encrypt.hint) || '';
    const title = attrs.title || '';
    const hasCustomPassword = Boolean((attrs.password || attrs.pass) && (attrs.password || attrs.pass) !== postPassword);

    let rawInner = renderMarkdownImages(block.innerContent);

    // 1. Check for <placeholder> / <mask> / <alt> tag
    const placeholderRegex = new RegExp(
      `<(${placeholderPattern})\\b[^>]*>([\\s\\S]*?)<\\/\\1>`,
      'i'
    );
    const placeholderMatch = rawInner.match(placeholderRegex);

    let placeholderHtml = '';
    let originalHtml = '';

    if (placeholderMatch) {
      // Custom placeholder tag explicitly specified
      placeholderHtml = placeholderMatch[2].trim();
      // Remove <placeholder> from innerContent to get original content
      originalHtml = rawInner.replace(placeholderRegex, '').trim();

      // Check if original content was wrapped in <content> / <raw>
      const contentRegex = new RegExp(
        `<(${contentPattern})\\b[^>]*>([\\s\\S]*?)<\\/\\1>`,
        'i'
      );
      const contentMatch = originalHtml.match(contentRegex);
      if (contentMatch) {
        originalHtml = contentMatch[2].trim();
      }

      // Process any images inside originalHtml (encrypt original images to Base64)
      const processedOriginal = await imageProcessor.processImages(originalHtml, postData);
      originalHtml = processedOriginal.encryptedHtml;

      // Also process any images inside placeholderHtml if any
      const processedPlaceholder = await imageProcessor.processImages(placeholderHtml, postData);
      placeholderHtml = processedPlaceholder.encryptedHtml;
    } else {
      // No <placeholder> tag
      // Check for placeholder/mask attribute: e.g. <enc mask="***">
      const customAttrPlaceholder = attrs.placeholder || attrs.mask || attrs.alt;

      // Extract original content (may be inside <content> / <raw> or raw)
      const contentRegex = new RegExp(
        `<(${contentPattern})\\b[^>]*>([\\s\\S]*?)<\\/\\1>`,
        'i'
      );
      const contentMatch = rawInner.match(contentRegex);
      if (contentMatch) {
        originalHtml = contentMatch[2].trim();
      } else {
        originalHtml = rawInner.trim();
      }

      // Process images: produces encrypted original data URLs and blurred image tags
      const { encryptedHtml, blurredHtml } = await imageProcessor.processImages(originalHtml, postData);
      originalHtml = encryptedHtml;

      if (customAttrPlaceholder) {
        placeholderHtml = `<span class="h-mask-txt">${escapeHtml(customAttrPlaceholder)}</span>`;
      } else {
        // Default replacement:
        // Text becomes default_text_placeholder ('***')
        // Images become Gaussian blurred images
        placeholderHtml = generateDefaultPlaceholder(blurredHtml, config.default_text_placeholder || '***');
      }
    }

    // 2. Encrypt originalHtml with password using AES-256-GCM
    const encryptedPayload = encrypt(originalHtml, password);

    // 3. Construct concise HTML container
    const isBlock = isBlockContent(placeholderHtml) || isBlockContent(originalHtml);
    const cipherBundle = `${encryptedPayload.salt}.${encryptedPayload.iv}.${encryptedPayload.tag}.${encryptedPayload.cipher}`;
    const hintAttr = hint ? ` data-hint="${escapeHtml(hint)}"` : '';
    const titleAttr = title ? ` data-title="${escapeHtml(title)}"` : '';
    const customAttr = hasCustomPassword ? ' data-custom="1"' : '';

    let outputHtml;
    if (isBlock) {
      outputHtml = `<div class="h-enc h-block" data-cipher="${cipherBundle}"${hintAttr}${titleAttr}${customAttr}><div class="h-mask">${placeholderHtml}</div></div>`;
    } else {
      outputHtml = `<span class="h-enc h-inline" data-cipher="${cipherBundle}"${hintAttr}${titleAttr}${customAttr}>${placeholderHtml}</span>`;
    }

    processedContent = processedContent.replace(block.fullMatch, outputHtml);
  }

  return {
    content: processedContent,
    hasEncryptedContent
  };
}

module.exports = {
  parseAndEncrypt,
  generateDefaultPlaceholder,
  isBlockContent,
  parseAttributes,
  renderMarkdownImages
};
